export const hotelTypes = [
  "Luxury",
  "Boutique",
  "Budget",
  "Resort",
  "Apartment",
  "Hostel",
  "Motel",
  "Guesthouse",
  "Lodge",
  "Business",
  "Eco-friendly",
  "All-inclusive",
  "Romantic",
  "Family",
  "Pet-friendly",
  "Adventure",
  "Wellness",
  "Heritage",
  "Urban",
  "Rural",
];

export const hotelFacilities = [
  "Free Wi-Fi",
  "Swimming Pool",
  "Fitness Center",
  "Spa",
  "Restaurant",
  "Bar",
  "Room Service",
  "Parking",
  "Airport Shuttle",
  "24-hour Front Desk",
  "Laundry Service",
  "Conference Rooms",
  "Business Center",
  "Pet-friendly",
  "Childcare Services",
  "Non-smoking Rooms",
  "Air Conditioning",
  "Mini Bar",
  "Cable TV",
  "Hair Dryer",
  "Tea/Coffee Maker",
  "Luggage Storage",
  "Outdoor Activities",
  "Tour Assistance",
  "Car Rental",
  "Sauna",
  "Game Room",
  "Private Beach",
  "Balcony/Terrace",
];
